---
services:

  mongodb:
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 37017:27017
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: eqalpha/keydb:arm64_v6.3.4
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 7379:6379
    volumes:
      - ./data/redis:/data
